# handling exceptions
# try:
#     file = open("data.txt")
#     a_dictionary = {"key":"value"}
#     print(a_dictionary["sadf"])
# except FileNotFoundError as e:
#     file = open("data.txt", "w")
#     file.write(f"Inside the exception!!... {e} ")
# except KeyError as key:
#     print(f'The key {key} does not exist')
# else:
#     content = file.read()
#     print(content)
# finally:
#     raise TypeError("Bad Type?")
